# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SARAA.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(759, 544)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 761, 551))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 0, 338, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.pilotLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.pilotLineEdit.setPlaceholderText("PILOT NAME")
        self.pilotLineEdit.setObjectName("pilotLineEdit")
        self.verticalLayout_2.addWidget(self.pilotLineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.insertPilotBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.insertPilotBtn.setObjectName("insertPilotBtn")
        self.horizontalLayout_2.addWidget(self.insertPilotBtn)
        self.editPilotBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.editPilotBtn.setObjectName("editPilotBtn")
        self.horizontalLayout_2.addWidget(self.editPilotBtn)
        self.deletePilotBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deletePilotBtn.setObjectName("deletePilotBtn")
        self.horizontalLayout_2.addWidget(self.deletePilotBtn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.aircraftLineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.aircraftLineEdit.setObjectName("aircraftLineEdit")
        self.verticalLayout.addWidget(self.aircraftLineEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insertAcBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.insertAcBtn.setObjectName("insertAcBtn")
        self.horizontalLayout.addWidget(self.insertAcBtn)
        self.editAcBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.editAcBtn.setObjectName("editAcBtn")
        self.horizontalLayout.addWidget(self.editAcBtn)
        self.deleteAcBtn = QtWidgets.QPushButton(self.layoutWidget)
        self.deleteAcBtn.setObjectName("deleteAcBtn")
        self.horizontalLayout.addWidget(self.deleteAcBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(self.tab)
        self.line.setGeometry(QtCore.QRect(0, 180, 701, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 200, 738, 102))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 3, 1, 1)
        self.insertLogBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.insertLogBtn.setObjectName("insertLogBtn")
        self.gridLayout.addWidget(self.insertLogBtn, 1, 6, 1, 1)
        self.printLogBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.printLogBtn.setObjectName("printLogBtn")
        self.gridLayout.addWidget(self.printLogBtn, 2, 6, 1, 1)
        self.acPrintCombo_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.acPrintCombo_2.setObjectName("acPrintCombo_2")
        self.gridLayout.addWidget(self.acPrintCombo_2, 2, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.cdbCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.cdbCheckBox.setObjectName("cdbCheckBox")
        self.horizontalLayout_3.addWidget(self.cdbCheckBox)
        self.dateTimeEdit_1 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit_1.setObjectName("dateTimeEdit_1")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.horizontalLayout_3.addWidget(self.dateTimeEdit_2)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 5, 1, 1)
        self.pilot1InsertCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pilot1InsertCombo.setEditable(False)
        self.pilot1InsertCombo.setObjectName("pilot1InsertCombo")
        self.gridLayout.addWidget(self.pilot1InsertCombo, 1, 0, 1, 1)
        self.acInsertCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.acInsertCombo.setObjectName("acInsertCombo")
        self.gridLayout.addWidget(self.acInsertCombo, 1, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 2, 1, 1)
        self.pilotPrintCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pilotPrintCombo.setObjectName("pilotPrintCombo")
        self.gridLayout.addWidget(self.pilotPrintCombo, 2, 0, 1, 1)
        self.lineEditPrint = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEditPrint.setObjectName("lineEditPrint")
        self.gridLayout.addWidget(self.lineEditPrint, 2, 5, 1, 1)
        self.pilot2insertCombo = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.pilot2insertCombo.setObjectName("pilot2insertCombo")
        self.gridLayout.addWidget(self.pilot2insertCombo, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(0, 320, 1061, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(10, 340, 711, 171))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 10, 340, 184))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "PILOT NAME"))
        self.insertPilotBtn.setText(_translate("Dialog", "INSERT"))
        self.editPilotBtn.setText(_translate("Dialog", "EDIT"))
        self.deletePilotBtn.setText(_translate("Dialog", "DELETE"))
        self.label.setText(_translate("Dialog", "AIRCRAFT"))
        self.aircraftLineEdit.setPlaceholderText(_translate("Dialog", "REGISTRATION"))
        self.insertAcBtn.setText(_translate("Dialog", "INSERT"))
        self.editAcBtn.setText(_translate("Dialog", "EDIT"))
        self.deleteAcBtn.setText(_translate("Dialog", "DELETE"))
        self.label_3.setText(_translate("Dialog", "AIRCRAFT"))
        self.insertLogBtn.setText(_translate("Dialog", "INSERT"))
        self.printLogBtn.setText(_translate("Dialog", "PRINT"))
        self.label_4.setText(_translate("Dialog", "PILOT1"))
        self.cdbCheckBox.setText(_translate("Dialog", "CDB"))
        self.label_5.setText(_translate("Dialog", "PILOT2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Tab 2"))

